-- Create and seed the local organization applied-title directory.

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS `tblorganizations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nameen` varchar(255) NOT NULL,
  `namefr` varchar(255) NOT NULL,
  `abbreviationen` varchar(50) DEFAULT NULL,
  `abbreviationfr` varchar(50) DEFAULT NULL,
  `source_part` tinyint(1) NOT NULL DEFAULT 0,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tblorganizations_nameen` (`nameen`),
  UNIQUE KEY `uq_tblorganizations_namefr` (`namefr`),
  KEY `idx_tblorganizations_status_nameen` (`status`, `nameen`),
  KEY `idx_tblorganizations_status_namefr` (`status`, `namefr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `tblorganizations`
  MODIFY `source_part` tinyint(1) NOT NULL DEFAULT 0;

-- Official organization applied-title snapshot.
-- Sources: GC Open Data Part 1 and TBS Federal Identity Program registry Part 2.
-- Retrieved: 2026-07-27. Runtime intake does not access these external sources.

INSERT INTO `tblorganizations` (`nameen`, `namefr`, `abbreviationen`, `abbreviationfr`, `source_part`, `status`) VALUES
('Accessibility Standards Canada', 'Normes d''accessibilité Canada', 'ASC', 'NAC', 1, 1),
('Administrative Tribunals Support Service of Canada', 'Service canadien d''appui aux tribunaux administratifs', 'ATSSC', 'SCDATA', 1, 1),
('Agriculture and Agri-Food Canada', 'Agriculture et Agroalimentaire Canada', 'AAFC', 'AAC', 1, 1),
('Atlantic Canada Opportunities Agency', 'Agence de promotion économique du Canada atlantique', 'ACOA', 'APECA', 1, 1),
('Build Canada Homes', 'Maisons Canada', 'BCH', 'MC', 2, 1),
('Canada Agricultural Review Tribunal', 'Commission de révision agricole du Canada', 'CART', 'CRAC', 2, 1),
('Canada Border Services Agency', 'Agence des services frontaliers du Canada', 'CBSA', 'ASFC', 1, 1),
('Canada Economic Development for Quebec Regions', 'Développement économique Canada pour les régions du Québec', 'CED', 'DEC', 1, 1),
('Canada Emission Reduction Incentives Agency', 'Agence canadienne pour l''incitation à la réduction des émissions', NULL, NULL, 1, 1),
('Canada Employment Insurance Commission', 'Commission de l''assurance-emploi du Canada', 'CEIC', 'CAEC', 1, 1),
('Canada Energy Regulator', 'Régie de l''énergie du Canada', 'CER', 'REC', 1, 1),
('Canada Industrial Relations Board', 'Conseil canadien des relations industrielles', 'CIRB', 'CCRI', 2, 1),
('Canada Ombudsperson for Responsible Enterprise', 'Ombudsman du Canada de la responsabilité des entreprises', 'CORE', 'OCRE', 2, 1),
('Canada Research Chairs', 'Chaires de recherche du Canada', NULL, NULL, 2, 1),
('Canada Revenue Agency', 'Agence du revenu du Canada', 'CRA', 'ARC', 1, 1),
('Canada School of Public Service', 'École de la fonction publique du Canada', 'CSPS', 'EFPC', 1, 1),
('Canada Water Agency', 'Agence de l’eau du Canada', 'CWA', 'AEC', 1, 1),
('Canadian Centre for Occupational Health and Safety', 'Centre canadien d''hygiène et de sécurité au travail', 'CCOHS', 'CCHST', 1, 1),
('Canadian Coast Guard', 'Garde côtière canadienne', 'CCG', 'GCC', 2, 1),
('Canadian Conservation Institute', 'Institut canadien de conservation', 'CCI', 'ICC', 2, 1),
('Canadian Cultural Property Export Review Board', 'Commission canadienne d’examen des exportations de biens culturels', 'CCPERB', 'CCEEBC', 2, 1),
('Canadian Food Inspection Agency', 'Agence canadienne d''inspection des aliments', 'CFIA', 'ACIA', 1, 1),
('Canadian Grain Commission', 'Commission canadienne des grains', 'CGC', 'CCG', 1, 1),
('Canadian Heritage', 'Patrimoine canadien', 'PCH', 'PCH', 1, 1),
('Canadian Heritage Information Network', 'Réseau canadien d''information sur le patrimoine', 'CHIN', 'RCIP', 2, 1),
('Canadian Human Rights Commission', 'Commission canadienne des droits de la personne', 'CHRC', 'CCDP', 1, 1),
('Canadian Human Rights Tribunal', 'Tribunal canadien des droits de la personne', 'CHRT', 'TCDP', 2, 1),
('Canadian Institutes of Health Research', 'Instituts de recherche en santé du Canada', 'CIHR', 'IRSC', 1, 1),
('Canadian Intellectual Property Office', 'Office de la propriété intellectuelle du Canada', 'CIPO', 'OPIC', 2, 1),
('Canadian Intergovernmental Conference Secretariat', 'Secrétariat des conférences intergouvernementales canadiennes', 'CICS', 'SCIC', 1, 1),
('Canadian Northern Economic Development Agency', 'Agence canadienne de développement économique du Nord', 'CanNor', 'CanNor', 1, 1),
('Canadian Nuclear Safety Commission', 'Commission canadienne de sûreté nucléaire', 'CNSC', 'CCSN', 1, 1),
('Canadian Radio-television and Telecommunications Commission', 'Conseil de la radiodiffusion et des télécommunications canadiennes', 'CRTC', 'CRTC', 1, 1),
('Canadian Security Intelligence Service', 'Service canadien du renseignement de sécurité', 'CSIS', 'SCRS', 1, 1),
('Canadian Space Agency', 'Agence spatiale canadienne', 'CSA', 'ASC', 1, 1),
('Canadian Transportation Agency', 'Office des transports du Canada', 'CTA', 'OTC', 1, 1),
('Civilian Review and Complaints Commission for the RCMP', 'Commission civile d’examen et de traitement des plaintes relatives à la GRC', 'CRCC', 'CCETP', 1, 1),
('Communications Research Centre Canada', 'Centre de recherches sur les communications Canada', 'CRC', 'CRC', 2, 1),
('Communications Security Establishment Canada', 'Centre de la sécurité des télécommunications Canada', 'CSE', 'CST', 1, 1),
('Competition Bureau Canada', 'Bureau de la concurrence Canada', 'COBU', 'BUCO', 2, 1),
('Copyright Board Canada', 'Commission du droit d''auteur Canada', 'CB', 'CDA', 1, 1),
('Correctional Service Canada', 'Service correctionnel Canada', 'CSC', 'SCC', 1, 1),
('Courts Administration Service', 'Service administratif des tribunaux judiciaires', 'CAS', 'SATJ', 1, 1),
('Crown-Indigenous Relations and Northern Affairs Canada', 'Relations Couronne-Autochtones et Affaires du Nord Canada', 'CIRNAC', 'RCAANC', 1, 1),
('Defence Research and Development Canada', 'Recherche et développement pour la défense Canada', 'DRDC', 'RDDC', 2, 1),
('Department of Finance Canada', 'Ministère des Finances Canada', 'FIN', 'FIN', 1, 1),
('Department of Justice Canada', 'Ministère de la Justice Canada', 'JUS', 'JUS', 1, 1),
('Employment and Social Development Canada', 'Emploi et Développement social Canada', 'ESDC', 'EDSC', 1, 1),
('Environmental Protection Tribunal of Canada', 'Tribunal de la protection de l''environnement du Canada', 'EPTC', 'TPEC', 2, 1),
('Environment and Climate Change Canada', 'Environnement et Changement climatique Canada', 'ECCC', 'ECCC', 1, 1),
('Farm Products Council of Canada', 'Conseil des produits agricoles du Canada', 'FPCC', 'CPAC', 1, 1),
('Federal Economic Development Agency for Northern Ontario', 'Agence fédérale de développement économique pour le Nord de l''Ontario', 'FedNor', 'FedNor', 1, 1),
('Federal Economic Development Agency for Southern Ontario', 'Agence fédérale de développement économique pour le Sud de l''Ontario', 'FedDev Ontario', 'FedDev Ontario', 1, 1),
('Financial Consumer Agency of Canada', 'Agence de la consommation en matière financière du Canada', 'FCAC', 'ACFC', 1, 1),
('Financial Transactions and Reports Analysis Centre of Canada', 'Centre d''analyse des opérations et déclarations financières du Canada', 'FINTRAC', 'CANAFE', 1, 1),
('Fisheries and Oceans Canada', 'Pêches et Océans Canada', 'DFO', 'MPO', 1, 1),
('Global Affairs Canada', 'Affaires mondiales Canada', 'GAC', 'AMC', 1, 1),
('Government of Canada', 'Gouvernement du Canada', 'GC', 'GC', 1, 1),
('Health Canada', 'Santé Canada', 'HC', 'SC', 1, 1),
('Health Emergency Readiness Canada', 'Préparation aux crises sanitaires Canada', 'HERC', 'PCSC', 2, 1),
('Historic Sites and Monuments Board of Canada', 'Commission des lieux et monuments historiques du Canada', 'HSMBC', 'CLMHC', 2, 1),
('Housing, Infrastructure and Communities Canada', 'Logement, Infrastructures et Collectivités Canada', 'HICC', 'LICC', 1, 1),
('Immigration, Refugees and Citizenship Canada', 'Immigration, Réfugiés et Citoyenneté Canada', 'IRCC', 'IRCC', 1, 1),
('Immigration and Refugee Board of Canada', 'Commission de l''immigration et du statut de réfugié du Canada', 'IRB', 'CISR', 1, 1),
('Impact Assessment Agency of Canada', 'Agence d''évaluation d''impact du Canada', 'IAAC', 'AEIC', 1, 1),
('Indigenous Services Canada', 'Services aux Autochtones Canada', 'ISC', 'SAC', 1, 1),
('Innovation, Science and Economic Development Canada', 'Innovation, Sciences et Développement économique Canada', 'ISED', 'ISDE', 1, 1),
('Invest in Canada Hub', 'Investir au Canada', NULL, NULL, 1, 1),
('Law Commission of Canada', 'Commission du droit du Canada', NULL, NULL, 1, 1),
('Leaders'' Debates Commission', 'Commission des débats des chefs', NULL, NULL, 1, 1),
('Library and Archives Canada', 'Bibliothèque et Archives Canada', 'LAC', 'BAC', 1, 1),
('Major Projects Office of Canada', 'Bureau des grands projets du Canada', 'MPO', 'BGP', 2, 1),
('Measurement Canada', 'Mesures Canada', 'MC', 'MC', 2, 1),
('Military Grievances External Review Committee', 'Comité externe d''examen des griefs militaires', 'MGERC', 'CEEGM', 1, 1),
('Military Police Complaints Commission of Canada', 'Commission d''examen des plaintes concernant la police militaire du Canada', 'MPCC', 'CPPM', 1, 1),
('National Defence', 'Défense nationale', 'DND', 'MDN', 1, 1),
('National Film Board', 'Office national du film', 'NFB', 'ONF', 1, 1),
('National Research Council Canada', 'Conseil national de recherches Canada', 'NRC', 'CNRC', 1, 1),
('National Security and Intelligence Review Agency Secretariat', 'Secrétariat de l''Office de surveillance des activités en matière de sécurité nationale et de renseignement', NULL, NULL, 1, 1),
('Natural Resources Canada', 'Ressources naturelles Canada', 'NRCan', 'RNCan', 1, 1),
('Natural Sciences and Engineering Research Council of Canada', 'Conseil de recherches en sciences naturelles et en génie du Canada', 'NSERC', 'CRSNG', 1, 1),
('Northern Pipeline Agency Canada', 'Administration du pipe-line du Nord Canada', 'NPA', 'APN', 1, 1),
('Office of the Auditor General of Canada', 'Bureau du vérificateur général du Canada', 'OAG', 'BVG', 1, 1),
('Office of the Chief Accessibility Officer of Canada', 'Bureau de la dirigeante principale de l’accessibilité du Canada', 'OCAO', 'BDPA', 2, 1),
('Office of the Chief Electoral Officer', 'Bureau du directeur général des élections', 'elections', 'elections', 1, 1),
('Office of the Chief Science Advisor of Canada', 'Bureau du conseiller scientifique en chef du Canada', 'OCSA', 'BCSC', 2, 1),
('Office of the Commissioner for Federal Judicial Affairs Canada', 'Commissariat à la magistrature fédérale Canada', 'FJA', 'CMF', 1, 1),
('Office of the Commissioner of Lobbying of Canada', 'Commissariat au lobbying du Canada', 'OCL', 'CAL', 1, 1),
('Office of the Commissioner of Official Languages', 'Commissariat aux langues officielles', 'OCOL', 'CLO', 1, 1),
('Office of the Foreign Influence Commissioner of Canada', 'Commissariat à l''influence étrangère du Canada', 'OFICC', 'CIEC', 2, 1),
('Office of the Intelligence Commissioner', 'Bureau du commissaire au renseignement', NULL, NULL, 1, 1),
('Office of the Public Sector Integrity Commissioner of Canada', 'Commissariat à l''intégrité du secteur public du Canada', 'PSIC', 'ISPC', 1, 1),
('Office of the Secretary to the Governor General', 'Bureau du secrétaire du gouverneur général', 'OSGG', 'BSGG', 1, 1),
('Office of the Superintendent of Bankruptcy Canada', 'Bureau du surintendant des faillites Canada', 'OSB', 'BSF', 2, 1),
('Office of the Superintendent of Financial Institutions Canada', 'Bureau du surintendant des institutions financières Canada', 'OSFI', 'BSIF', 1, 1),
('Offices of the Information and Privacy Commissioners of Canada', 'Commissariats à l''information et à la protection de la vie privée au Canada', 'OPC', 'CPVP', 1, 1),
('Pacific Economic Development Canada', 'Développement économique Canada pour le Pacifique', 'PacifiCan', 'PacifiCan', 1, 1),
('Parks Canada', 'Parcs Canada', 'PC', 'PC', 1, 1),
('Parole Board of Canada', 'Commission des libérations conditionnelles du Canada', 'PBC', 'CLCC', 1, 1),
('Patented Medicine Prices Review Board Canada', 'Conseil d''examen du prix des médicaments brevetés Canada', 'PMPRB', 'CEPMB', 1, 1),
('Polar Knowledge Canada', 'Savoir polaire Canada', 'POLAR', 'POLAIRE', 1, 1),
('Policy Horizons Canada', 'Horizons de politiques Canada', 'PHC', 'HPC', 2, 1),
('Prairies Economic Development Canada', 'Développement économique Canada pour les Prairies', 'PrairiesCan', 'PrairiesCan', 1, 1),
('Privy Council Office', 'Bureau du Conseil privé', 'PCO', 'BCP', 1, 1),
('Public Health Agency of Canada', 'Agence de la santé publique du Canada', 'PHAC', 'ASPC', 1, 1),
('Public Prosecution Service of Canada', 'Service des poursuites pénales du Canada', 'PPSC', 'SPPC', 1, 1),
('Public Safety Canada', 'Sécurité publique Canada', 'PS', 'SP', 1, 1),
('Public Servants Disclosure Protection Tribunal Canada', 'Tribunal de la protection des fonctionnaires divulgateurs Canada', 'PSDPTC', 'TPFDC', 2, 1),
('Public Service Commission of Canada', 'Commission de la fonction publique du Canada', 'PSC', 'CFP', 1, 1),
('Public Service Labour Relations and Employment Board', 'Commission des relations de travail et de l''emploi dans la fonction publique', 'PSLREB', 'CRTEFP', 2, 1),
('Public Services and Procurement Canada', 'Services publics et Approvisionnement Canada', 'PSPC', 'SPAC', 1, 1),
('RCMP External Review Committee', 'Comité externe d''examen de la GRC', 'ERC', 'CEE', 1, 1),
('Registrar of the Supreme Court of Canada and that portion of the federal public administration appointed under subsection 12(2) of the Supreme Court Act', 'Registraire de la Cour suprême du Canada et le secteur de l''administration publique fédérale nommé en vertu du paragraphe 12(2) de la Loi sur la Cour suprême', 'SCC', 'CSC', 1, 1),
('Registry of the Specific Claims Tribunal of Canada', 'Greffe du Tribunal des revendications particulières du Canada', 'SCT', 'TRP', 2, 1),
('Royal Canadian Mounted Police', 'Gendarmerie royale du Canada', 'RCMP', 'GRC', 1, 1),
('Secretariat of the National Security and Intelligence Committee of Parliamentarians', 'Secrétariat du Comité des parlementaires sur la sécurité nationale et le renseignement', 'SNSICP', 'SCPSNR', 1, 1),
('Service Canada', 'Service Canada', 'ServCan', 'ServCan', 2, 1),
('Shared Services Canada', 'Services partagés Canada', 'SSC', 'SPC', 1, 1),
('Ship-source Oil Pollution Fund', 'Caisse d''indemnisation des dommages dus à la pollution par les hydrocarbures causée par les navires', NULL, NULL, 2, 1),
('Social Sciences and Humanities Research Council of Canada', 'Conseil de recherches en sciences humaines du Canada', 'SSHRC', 'CRSH', 1, 1),
('Social Security Tribunal of Canada', 'Tribunal de la sécurité sociale du Canada', 'SST', 'TSS', 2, 1),
('Statistics Canada', 'Statistique Canada', 'StatCan', 'StatCan', 1, 1),
('The Correctional Investigator Canada', 'L''Enquêteur correctionnel Canada', 'OCI', 'BEC', 1, 1),
('The National Battlefields Commission', 'Commission des champs de bataille nationaux', 'NBC', 'CCBN', 1, 1),
('Transportation Appeal Tribunal of Canada', 'Tribunal d''appel des transports du Canada', 'TATC', 'TATC', 2, 1),
('Transportation Safety Board of Canada', 'Bureau de la sécurité des transports du Canada', 'TSB', 'BST', 1, 1),
('Transport Canada', 'Transports Canada', 'TC', 'TC', 1, 1),
('Treasury Board', 'Conseil du Trésor', 'TB', 'CT', 1, 1),
('Treasury Board of Canada Secretariat', 'Secrétariat du Conseil du Trésor du Canada', 'TBS', 'SCT', 1, 1),
('Veterans Affairs Canada', 'Anciens Combattants Canada', 'VAC', 'ACC', 1, 1),
('Veterans Review and Appeal Board', 'Tribunal des anciens combattants (révision et appel)', 'VRAB', 'TACRA', 1, 1),
('Women and Gender Equality Canada', 'Femmes et Égalité des genres Canada', 'WAGE', 'FEGC', 1, 1)
ON DUPLICATE KEY UPDATE
  `namefr` = VALUES(`namefr`),
  `abbreviationen` = VALUES(`abbreviationen`),
  `abbreviationfr` = VALUES(`abbreviationfr`),
  `source_part` = VALUES(`source_part`);
