<?php
if (isset($_SERVER['SCRIPT_FILENAME']) && realpath(__FILE__) === realpath((string) $_SERVER['SCRIPT_FILENAME'])) {
    http_response_code(404);
    exit();
}

/**
 * GC Notify template preview metadata.
 * Keyed by GCNOTIFY_TEMPLATE_* setting names.
 */
function rmt_get_template_preview_definitions(): array
{
    return [
        'GCNOTIFY_TEMPLATE_ID' => [
            'slug' => 'notification-generic',
            'name_en' => 'Generic notification template',
            'name_fr' => 'Modèle de notification générique',
            'audience_en' => 'All notifications',
            'audience_fr' => 'Toutes les notifications',
            'language_order_en' => 'Body text supplied by the app',
            'language_order_fr' => 'Le corps du courriel est fourni par l\'application',
            'purpose_en' => 'Used for every GC Notify email. The app supplies the subject and main body through ((subject)) and ((message)).',
            'purpose_fr' => 'Utilisé pour tous les courriels GC Notify. L\'application fournit le sujet et le corps principal via ((subject)) et ((message)).',
            'subject_en' => 'Subject generated by the app',
            'subject_fr' => 'Objet généré par l application',
            'fr_first' => false,
        ],
    ];
}
